### ISSUE TITLE
这个上传组件和reactjs 0.14.x有冲突吗?

### ISSUE THREAD

**Issue by kokokele** [tianxiangbing/upload#1]
测试 非reactjs 实现的可以正常调用.  

reactjs 下点击上传按钮无反应.

最后感谢分享.

**Comment by tianxiangbing** [comment]
是这样的，如果是react的话，可能要在某个地方（angular有实例,react还不熟,应该也可以）把element传入upload，或者是改写upload代码，改成全委托到根节点的形式

**Comment by kokokele** [comment]
找到原因了, 似乎和react 无太大关系,  原因是父节点是隐藏的. 然后渲染完后我就执行 初始化upload.init了.
这时里面的 上传 btn根本没有被渲染.  

---

感谢这么快的回复.:>
